#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lineFollowerLeft, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerMid, sensorLineFollower)
#pragma config(Sensor, in5,    lineFollowerRight, sensorLineFollower)
#pragma config(Sensor, in6,    gyroSensor,     sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl6,  sonarIn,        sensorSONAR_mm)
#pragma config(Sensor, dgtl8,  ,               sensorDigitalIn)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!								Code automatically generated by 'ROBOTC' configuration wizard  									!!*//

void driveForward(){
	if(SensorValue[rightEncoder] == SensorValue[leftEncoder]) // If rightEncoder has counted the same amount as leftEncoder:
	{
		// Move Forward
		motor[rightMotor] = 80;		    // Right Motor is run at power level 80
		motor[leftMotor]  = 80;		    // Left Motor is run at power level 80
	}
	else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])	// If rightEncoder has counted more encoder counts
	{
		// Turn slightly right
		motor[rightMotor] = 60;		    // Right Motor is run at power level 60
		motor[leftMotor]  = 80;		    // Left Motor is run at power level 80
	}
	else	// Only runs if leftEncoder has counted more encoder counts
	{
		// Turn slightly left
		motor[rightMotor] = 80;		    // Right Motor is run at power level 80
		motor[leftMotor]  = 60;		    // Left Motor is run at power level 60
	}
}

void driveBackwards(){
	if(abs(SensorValue[rightEncoder]) == abs(SensorValue[leftEncoder])) // If rightEncoder has counted the same amount as leftEncoder:
	{
		// Move Forward
		abs(motor[rightMotor] = -80);		    // Right Motor is run at power level 80
		abs(motor[leftMotor]  = -80);		    // Left Motor is run at power level 80
	}
	else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])	// If rightEncoder has counted more encoder counts
	{
		// Turn slightly right
		abs(motor[rightMotor] = -60);		    // Right Motor is run at power level 60
		abs(motor[leftMotor]  = -80);		    // Left Motor is run at power level 80
	}
	else	// Only runs if leftEncoder has counted more encoder counts
	{
		// Turn slightly left
		abs(motor[rightMotor] = -80);		    // Right Motor is run at power level 80
		abs(motor[leftMotor]  = -60);		    // Left Motor is run at power level 60
	}
}

task main()
{
	//31.4 cm is the dimetion of the wheels
	//driveForward(); //Void that makes sure that the robot drives straight
	//driveBackwards(); //Void that makes sure that the robot drives straight in reverse

  SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;
	int i = 1;

	//50 cm / 31.4 cm = 1.59 -- 0.5 meters takes  spins of the wheel
	//360*1.59=572 -- The wheel needs to spin 572 degrees to move 0.5 meters

	float distance = 1.59;


	for(i=1; i < 6; i = i + 1){
		float spins  = 360 * distance;
  	while(SensorValue[rightEncoder]< spins && SensorValue[leftEncoder] < spins)
  	{
  	  driveForward();
  	}

		SensorValue[rightEncoder] = 0;
  	SensorValue[leftEncoder] = 0;
  	motor[rightMotor] = 0;
		motor[leftMotor]  = 0;
  	wait1Msec(1000);

 		while(SensorValue[rightEncoder]< spins && SensorValue[leftEncoder] < spins)
  	{
   		driveBackwards();
  	}

  	SensorValue[rightEncoder] = 0;
  	SensorValue[leftEncoder] = 0;
  	motor[rightMotor] = 0;
		motor[leftMotor]  = 0;
  	wait1Msec(1000);

  	distance = distance + 1.59;
	}
}
